apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: almq0obcq-nodejs 
  janus-idp.io/tekton: almq0obcq-nodejs
  backstage.io/kubernetes-id: almq0obcq-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: almq0obcq-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  