apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: almq0obcq-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/rhtap-qe:83e8fdfd2e0f5046671526dfcfd05e2fc1e6d535@sha256:8bd999aa30c14272ec7e188d173cdcd13c48d7fe79231ad243fa6803ffc74adf
          name: container-image
