apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: almq0obcq-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: almq0obcq-nodejs 
  name: almq0obcq-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: almq0obcq-nodejs 
